server:
  port: 8080

spring:
  application:
    name: pulse payment gateway

  datasource:
    url:  jdbc:mysql://localhost:3306/pulse?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: D!ck3n5@123

  jpa:
    show-sql: true

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900
    refreshTokenExpiration: 604800

  mpesa:
    consumerKey: ${MPESA_CONSUMER_KEY}
    consumerSecret: ${MPESA_CONSUMER_SECRET}
    passKey: ${MPESA_PASSKEY}
    authUrl: ${MPESA_AUTH}
    stkPushUrl: ${MPESA_STKPUSH}
    shortCode: ${MPESA_STK_SHORTCODE}
    callBackUrl: ${MPESA_CALLBACK}
    
  kafka:
    bootstrap-servers: localhost:9092

  webhook:
    maxAttempts: 6
    backoffSeconds: [ 60, 300, 1800, 7200, 28800, 86400 ] # 1m,5m,30m,2h,8h,24h

