server:
  port: 8080

spring:
  application:
    name: pulse payment gateway

  datasource:
    url:  jdbc:mysql://localhost:3306/pulse?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: D!ck3n5@123

  jpa:
    show-sql: true

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 # 15 minutes
    refreshTokenExpiration: 604800 # 7 days

  mpesa:
    consumerKey: ${MPESA_CONSUMER_KEY}
    consumerSecret: ${MPESA_CONSUMER_SECRET}
    passKey: ${MPESA_PASSKEY}
    authUrl: ${MPESA_AUTH}
    stkPushUrl: ${MPESA_STKPUSH}
    shortCode: ${MPESA_STK_SHORTCODE}
    callBackUrl: ${MPESA_CALLBACK}
    registerPaybillUrl: ${MPESA_PAYBILL_REGISTER_URLS}
    confirmationUrl: ${MPESA_CONFIRMATION}
    validationUrl: ${MPESA_VALIDATION}
